### ISSUE TITLE
관리자 확인이 제대로 되지 않음.

### ISSUE THREAD

**Issue by tercom** [kijk2869/Discord-Python-Notice-Korean#2]
480240821623455746
![image](https://user-images.githubusercontent.com/33586417/58358053-33398280-7eb8-11e9-9fbb-7d6ee0430bf1.png)

**Comment by kijk2869** [comment]
Identified

It occurred because of change type of user id

**Comment by kijk2869** [comment]
만약 추가로 오류가 더 일어난다면, 이 이슈를 다시 열어주세요
