### ISSUE TITLE
뮤직 채널에 공지

### ISSUE THREAD

**Issue by tercom** [kijk2869/Discord-Python-Notice-Korean#3]
File "C:\Users\Yoru\Downloads\요루의 작업공간\Discord-Python-Notice-Korean-master\main.py", line 61, in on_message
    await channel.send(notice)
AttributeError: 'VoiceChannel' object has no attribute 'send'

Voice Channel에 공지를 발신하려함..

**Comment by ttakkku** [comment]
&#8203;&#8203;&#8203;&#8203;

**Comment by kijk2869** [comment]
fixed on #09faa34
